### ISSUE TITLE
Add ability to specify proxy or import proxy settings

### ISSUE THREAD

**Issue by digital-shokunin** [sourcefrenchy/certexfil#1]
It would be good to have the ability to support proxy either through grabbing the system settings (Windows), or respecting the http_proxy/https_proxy env variables. Alternatively, allow the proxy to be specified as a command line option.

**Comment by sourcefrenchy** [comment]
hey there, I think my last commit should do the trick, works locally with a dummy Squid proxy and basic auth. Let me know!
